/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.placeholder.PlaceHolder;

/**
 *
 * @author Orlando
 */
public class ListaInventario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public ListaInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        holders();
    }
    public void holders(){
      PlaceHolder holder;  
      holder=new PlaceHolder(jtxtBuscar,"Buscar por Nombre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableListaInventario = new javax.swing.JTable();
        jtxtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jlblListaInventarioIcono = new javax.swing.JLabel();
        jlblListaInventario = new javax.swing.JLabel();
        jspListaInventario = new javax.swing.JSeparator();
        jlblCerrar = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelListaInventario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaInventario.setPreferredSize(new java.awt.Dimension(1000, 400));
        jPanelListaInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableListaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Nombre", "Descripcion", "Categoria", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableListaInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtableListaInventario.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane1.setViewportView(jtableListaInventario);
        if (jtableListaInventario.getColumnModel().getColumnCount() > 0) {
            jtableListaInventario.getColumnModel().getColumn(0).setMinWidth(50);
            jtableListaInventario.getColumnModel().getColumn(0).setMaxWidth(60);
            jtableListaInventario.getColumnModel().getColumn(1).setMinWidth(100);
            jtableListaInventario.getColumnModel().getColumn(1).setMaxWidth(110);
            jtableListaInventario.getColumnModel().getColumn(5).setMinWidth(100);
            jtableListaInventario.getColumnModel().getColumn(5).setMaxWidth(110);
        }

        jPanelListaInventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 760, 230));

        jtxtBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtxtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBuscar.setBorder(null);
        jtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarActionPerformed(evt);
            }
        });
        jPanelListaInventario.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 20));

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanelListaInventario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_32px.png"))); // NOI18N
        jPanelListaInventario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaBuscarb.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaBuscar.png"))); // NOI18N
        btnBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaBuscar.png"))); // NOI18N
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaBuscar.png"))); // NOI18N
        jPanelListaInventario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 75, 25));

        jlblListaInventarioIcono.setBackground(new java.awt.Color(255, 255, 255));
        jlblListaInventarioIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/categoria.png"))); // NOI18N
        jPanelListaInventario.add(jlblListaInventarioIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jlblListaInventario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jlblListaInventario.setForeground(new java.awt.Color(102, 102, 102));
        jlblListaInventario.setText("Lista de Inventario");
        jPanelListaInventario.add(jlblListaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 17, -1, -1));
        jPanelListaInventario.add(jspListaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, -1));

        jlblCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jlblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jlblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCerrarMouseClicked(evt);
            }
        });
        jPanelListaInventario.add(jlblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaSeleccionarb.png"))); // NOI18N
        btnSeleccionar.setBorder(null);
        btnSeleccionar.setBorderPainted(false);
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaSeleccionar.png"))); // NOI18N
        btnSeleccionar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaSeleccionar.png"))); // NOI18N
        btnSeleccionar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CajaSeleccionar.png"))); // NOI18N
        jPanelListaInventario.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 362, 85, 25));

        getContentPane().add(jPanelListaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarActionPerformed

    private void jlblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCerrarMouseClicked
        EntradaNuevo form = new EntradaNuevo();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelListaInventario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel jlblCerrar;
    private javax.swing.JLabel jlblListaInventario;
    private javax.swing.JLabel jlblListaInventarioIcono;
    public javax.swing.JSeparator jspListaInventario;
    public javax.swing.JTable jtableListaInventario;
    public javax.swing.JTextField jtxtBuscar;
    // End of variables declaration//GEN-END:variables
}
